# Contoh 3

Carilah nilai untuk x1, x2, x3, dan x4 dari persamaan sistem linear dibawah ini :

    x1 + x2 + x4 = 3
    x1 + 2*x2 + x3 = 1
    x2 + x3 - x4 = -2

pada contoh ini kita menggunakan nilai x1, x2, dan seterusnya, hal ini disebabkan jika kita memiliki variabel lebih dari 3

In [3]:
import numpy as np

A = np.array([[1.,1,0,1,3], [1, 2, 1, 0, 1], [0, 1, 1, -1, -2]]);
r1 = A[0,:]
r2 = A[1,:]
r3 = A[2,:]

A = np.array([r1,r2-r1,r3])

r1 = A[0,:]
r2 = A[1,:]
r3 = A[2,:]
A = np.array([r1,r2,r3-r2])

r1 = A[0,:]
r2 = A[1,:]
r3 = A[2,:]
A = np.array([r1-r2,r2,r3])
print('Row Echelon for our Linear system Equation \n' + str(A))


Row Echelon for our Linear system Equation 
[[ 1.  0. -1.  2.  5.]
 [ 0.  1.  1. -1. -2.]
 [ 0.  0.  0.  0.  0.]]


In [4]:
x1 = 6
x2 = -2
x3 = -1
x4 = -1;
first_check = np.array([x1+x2+x4, x1+2*x2+x3, x2+x3-x4])
print('first check output = ' + str(first_check))

first check output = [ 3  1 -2]


In [5]:
x1 = 5
x2 = -2
x3 = 0
x4 = 0
second_check = np.array([x1+x2+x4, x1+2*x2+x3, x2+x3-x4])
print('second check output = ' + str(second_check))

second check output = [ 3  1 -2]


In [6]:
x1 = 4
x2 = -2
x3 = 1
x4 = 1
third_check = np.array([x1+x2+x4, x1+2*x2+x3, x2+x3-x4])
print('third check output =' + str(third_check))

third check output =[ 3  1 -2]
