# Chapter 1, Section 1 Part 4


Tujuan dari pelajaran kali ini adalah untuk mengenalkan bentuk eselon baris

In [15]:
from sympy import Matrix
import numpy as np

A = np.array([[1,1,0,-1],
              [0,1,-1,-7],
              [1,-3,2,19]])
r1 = A[0,:]
r2 = A[1,:]
r3 = A[2,:]
A = np.array([r1,
              r2,
              r3-r1])
r1 = A[0,:]
r2 = A[1,:]
r3 = A[2,:]
A = np.array([r1,
              r2,
              r3+4*r2])
r1 = A[0,:]
r2 = A[1,:]
r3 = A[2,:]
A = np.array([r1,
              r2,
              r3*-1/2])
r1 = A[0,:]
r2 = A[1,:]
r3 = A[2,:]
A = np.array([r1,
              r2+r3,
              r3])

r1 = A[0,:]
r2 = A[1,:]
r3 = A[2,:]
A = np.array([r1-r2,
              r2,
              r3])
print('Hasil nilai sistem x, y, dan z dari cara manual \n' + str(A))

Hasil nilai sistem x, y, dan z dari cara manual 
[[ 1.  0.  0.  2.]
 [ 0.  1.  0. -3.]
 [ 0.  0.  1.  4.]]


In [14]:
x = 2
y = -3
z = 4
output = np.array([x+y, y-z, x-3*y+2*z])
print('Nilai Keluaran dari persamaan sistem linear yang telah kita selesaikan \n' + str(output))

Nilai Keluaran dari persamaan sistem linear yang telah kita selesaikan 
[-1 -7 19]


In [13]:
# Fast Method
A = Matrix([[1,1,0,-1],
              [0,1,-1,-7],
              [1,-3,2,19]])
system, piv = A.rref()
print(str(system))

Matrix([[1, 0, 0, 2], [0, 1, 0, -3], [0, 0, 1, 4]])
