# Contoh 4 :

Diberikan sebuah matrix :
$$A = \begin{pmatrix} 1 & 2 & 3\\ -1 & 1 & 2 \end{pmatrix}, B = \begin{pmatrix} 3 & 0\\1 & 1\\0 & 2 \end{pmatrix}, C = \begin{pmatrix} 1 & 0 & 1 & 2\\ 1 & 3 & 4 & 1 \end{pmatrix} $$

buktikanlah bahawa $$(AB)C = A(BC)$$

In [4]:
import numpy as np

A = np.array([[1,2,3],[-1,1,2]])
B = np.array([[3,0],[1,1],[0,2]])
C = np.array([[1,0,1,2],[1,3,4,1]])

# First Method
dist_1 = np.dot(np.dot(A, B), C)
print(dist_1)

[[13 24 37 18]
 [ 3 15 18  1]]


In [5]:
# Cek apakah (AB)C sama dengan A(BC)
dist_2 = np.dot(A, np.dot(B, C))
print(dist_1 == dist_2)

[[ True  True  True  True]
 [ True  True  True  True]]


In [6]:
# Second Method
dist_1 = (A @ B) @ C
print(dist_1)

[[13 24 37 18]
 [ 3 15 18  1]]


In [7]:
# Cek apakah (AB)C sama dengan A(BC)
dist_2 = A @ (B @ C)
print(dist_1 == dist_2)

[[ True  True  True  True]
 [ True  True  True  True]]
