## Contoh #2 :

Diberikan matriks 
$A = \begin{pmatrix} 1 & 2 & 0\\ 3 & 0 & 1\\-1 & 4 & 2\end{pmatrix}, B = \begin{pmatrix} 2 & 1 & 1\\3 & -2 & 1\\1 & 1 & 1\end{pmatrix}$



Buktikan bahwa $(AB)^{-1} = B^{-1}A^{-1}$ menggunakan python

In [1]:
from numpy import array,dot
from numpy.linalg import inv

A = array([[1.,2,0],[3,0,1],[-1,4,2]])
B = array([[2.,1,1],[3,-2,1],[1,1,1]])
C = dot(A,B)
D = inv(C)
print(D)

[[ 0.88888889 -0.11111111 -0.44444444]
 [ 0.24074074  0.07407407 -0.2037037 ]
 [-1.7962963   0.37037037  0.98148148]]


In [4]:
inv_B = inv(B)
inv_A = inv(A)
D2 = dot(inv_B,inv_A)
print(D2)

[[ 0.88888889 -0.11111111 -0.44444444]
 [ 0.24074074  0.07407407 -0.2037037 ]
 [-1.7962963   0.37037037  0.98148148]]


Dari hasil diatas dapat kita lihat dan buktikan bahwa $(AB)^{-1} = B^{-1}A^{-1}$