# Contoh #2

Carilah inverse dari matriks 
$$A = \begin{pmatrix} 1 & 3 & -2\\ 2 & 3 & 0\\ 0 & 1 & -1\end{pmatrix}$$

In [11]:
# Cara Pertama untuk mencari inverse dari matriks A
# Menggunakan module numpy

from numpy import array
from numpy.linalg import inv

A = array([[1,3,-2],
             [2,3,0],
             [0,1,-1]])
A_inv = inv(A)
print('Inverse dari matriks A adalah \n' + str(A_inv))


Inverse dari matriks A adalah 
[[ 3. -1. -6.]
 [-2.  1.  4.]
 [-2.  1.  3.]]


In [12]:
# Cara kedua untuk mencari inverse matriks A 
# dengan metode menggabungkan matriks A dengan matriks identitas
# lalu mencari bentuk eselon dari matriks yang telah digabung tersebut
# Metode ini menggunakan modul sympy

from sympy import Matrix,eye

A = Matrix([[1,3,-2],[2,3,0],[0,1,-1]])
I = eye(3)
M = A.row_join(I)
M_rref_matrix, M_rref_pivots = M.rref()
print(M_rref_matrix)

Matrix([[1, 0, 0, 3, -1, -6], [0, 1, 0, -2, 1, 4], [0, 0, 1, -2, 1, 3]])
