## Contoh #4:

Carilah matriks inverse dari :
$$ A = \begin{pmatrix} 1 & 3 & -2\\2 & 3 & 0\\0 & 1 & -1\end{pmatrix} $$

In [3]:
from numpy import array
from numpy.linalg import inv

# Cara 1
A = array([[1,3,-2],[2,3,0],[0,1,-1]])
A_inverse = inv(A)
print('Inverse of A = \n ' + str(A_inverse))

Inverse of A = 
 [[ 3. -1. -6.]
 [-2.  1.  4.]
 [-2.  1.  3.]]


In [4]:
# Cara kedua

from sympy import Matrix,eye

A = Matrix([[1,3,-2],[2,3,0],[0,1,-1]])
B = eye(3)
M = A.row_join(B)
M_matrix, M_pivot = M.rref()
A_inv = M_matrix[0:3,3:6]
print('Inverse of A = \n' + str(A_inv))

Inverse of A = 
Matrix([[3, -1, -6], [-2, 1, 4], [-2, 1, 3]])
